'use client';
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useMemo, useState } from 'react';
import { createManagedContent, deleteManagedContent, getManagedContent, updateManagedContent, type ContentCollection } from '@/lib/admin/contentStore';
import type { ManagedContent, ManagedContentInput, ManagedContentStatus } from '@/types/admin';
import { AdminIcon } from './AdminIcons';
import { DateInput } from './DateInput';
import { AdminShell } from './AdminShell';
import styles from './admin.module.css';
import { formatAdminDate, parseAdminDate, toAdminDateInput, toStoredAdminDate } from '@/lib/admin/dateUtils';

const dateLabel = (date: string) => formatAdminDate(date);

type Props = { collection: ContentCollection; singular: string; title: string; subtitle: string };

export const ContentManager = ({ collection, singular, title, subtitle }: Props) => {
  const [items, setItems] = useState<ManagedContent[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('All');
  const [status, setStatus] = useState('All');
  const [form, setForm] = useState<ManagedContent | null | undefined>(undefined);
  const [view, setView] = useState<ManagedContent | null>(null);
  const [remove, setRemove] = useState<ManagedContent | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [dateError, setDateError] = useState('');
  const [dateInput, setDateInput] = useState('');
  const refresh = async () => { setItems(await getManagedContent(collection)); setLoading(false); };
  useEffect(() => { void refresh(); }, [collection]);
  useEffect(() => { setDateInput(form ? toAdminDateInput(form.publishDate) : ''); setDateError(''); }, [form]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(null), 3000); return () => window.clearTimeout(timer); }, [notice]);
  const categories = useMemo(() => Array.from(new Set(items.map((item) => item.category))), [items]);
  const filtered = items.filter((item) => (!search || [item.title, item.client, item.category].join(' ').toLowerCase().includes(search.toLowerCase())) && (category === 'All' || item.category === category) && (status === 'All' || item.status === status));
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const enteredDate = dateInput; const value: ManagedContentInput = { title: String(data.get('title') || ''), category: String(data.get('category') || ''), client: String(data.get('client') || ''), publishDate: toStoredAdminDate(enteredDate), shortDescription: String(data.get('shortDescription') || ''), content: String(data.get('content') || ''), link: String(data.get('link') || ''), status: String(data.get('status')) as ManagedContentStatus }; if (!value.title || !value.category || !value.shortDescription || !value.content) { setNotice('Please complete the required fields.'); return; } if (enteredDate && !parseAdminDate(enteredDate)) { setDateError('Use a valid date in DD:MM:YYYY format.'); return; } setDateError(''); if (form) await updateManagedContent(collection, form.id, value); else await createManagedContent(collection, value); setForm(undefined); await refresh(); setNotice(`${singular} saved successfully.`); };
  const flipStatus = async (item: ManagedContent) => { await updateManagedContent(collection, item.id, { ...item, status: item.status === 'Draft' ? 'Published' : 'Draft' }); await refresh(); setNotice(`${singular} status updated.`); };
  const confirmRemove = async () => { if (!remove) return; await deleteManagedContent(collection, remove.id); setRemove(null); await refresh(); setNotice(`${singular} deleted.`); };
  return <AdminShell title={title} subtitle={subtitle} action={<button className={styles.primaryButton} onClick={() => setForm(null)}><AdminIcon name="plus" />Add {singular}</button>}>
    {notice && <div className={styles.notice} role="status"><AdminIcon name="check"/>{notice}</div>}
    <section className={styles.panel}><header className={styles.tableHeader}><div><h2>All {title.toLowerCase()}</h2><p>{loading ? 'Loading local entries…' : `${filtered.length} entries found`}</p></div><div className={styles.filterBar}><label className={styles.searchField} data-search-box><span className={styles.searchIconWrap}><AdminIcon name="search"/></span><input data-search-input type="text" value={search} onChange={(e) => setSearch(e.target.value)} placeholder={`Search ${title.toLowerCase()}`} /></label><select value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Filter category"><option>All</option>{categories.map((value) => <option key={value}>{value}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter status"><option>All</option><option>Published</option><option>Draft</option></select></div></header>
      {loading ? <div className={styles.loadingState}><span className={styles.spinner}/>Loading entries…</div> : <div className={styles.tableWrap}><table className={styles.blogTable}><thead><tr><th>{singular}</th><th>Category</th><th>Client</th><th>Date</th><th>Status</th><th/></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><div className={styles.blogTitleCell}><span className={styles.blogInitial}>{item.title[0]}</span><div><strong>{item.title}</strong><span>{item.shortDescription}</span></div></div></td><td>{item.category}</td><td>{item.client || '—'}</td><td>{dateLabel(item.publishDate)}</td><td><button className={`${styles.status} ${item.status === 'Published' ? styles.published : styles.draft}`} onClick={() => flipStatus(item)}>{item.status}</button></td><td><div className={styles.rowActions}><button onClick={() => setView(item)} aria-label={`View ${item.title}`}><AdminIcon name="eye"/></button><button onClick={() => setForm(item)} aria-label={`Edit ${item.title}`}><AdminIcon name="edit"/></button><button className={styles.deleteAction} onClick={() => setRemove(item)} aria-label={`Delete ${item.title}`}><AdminIcon name="trash"/></button></div></td></tr>)}</tbody></table>{!filtered.length && <div className={styles.emptyState}><span className={styles.emptyIcon}><AdminIcon name="blogs"/></span><strong>No {title.toLowerCase()} found.</strong><button className={styles.secondaryButton} onClick={() => setForm(null)}>Add {singular}</button></div>}</div>}
    </section>
    {form !== undefined && <div className={styles.modalLayer} role="dialog" aria-modal="true"><button className={styles.modalBackdrop} onClick={() => setForm(undefined)} aria-label="Close"/><form key={form?.id || 'new'} className={`${styles.modal} ${styles.formModal} ${styles.contentForm}`} onSubmit={save}><header className={styles.modalHeader}><div><p className={styles.eyebrow}>{form ? 'EDIT ENTRY' : 'NEW ENTRY'}</p><h2>{form ? `Edit ${singular.toLowerCase()}` : `Create ${singular.toLowerCase()}`}</h2></div><button type="button" className={styles.iconButton} onClick={() => setForm(undefined)} aria-label="Close"><AdminIcon name="close"/></button></header><div className={styles.blogForm}><label className={styles.fullField}>Title<input name="title" defaultValue={form?.title} required/></label><label>Category<input name="category" defaultValue={form?.category} required/></label><label>Client / owner<input name="client" defaultValue={form?.client}/></label><label className={styles.dateField}>Publish date <span>(DD:MM:YYYY)</span><DateInput value={dateInput} onChange={setDateInput} error={dateError} aria-label="Publish date (DD:MM:YYYY)" /></label><label>Status<select name="status" defaultValue={form?.status || 'Draft'}><option>Draft</option><option>Published</option></select></label><label className={styles.fullField}>Short description<textarea name="shortDescription" rows={3} defaultValue={form?.shortDescription} required/></label><label className={styles.fullField}>Content<textarea name="content" rows={7} defaultValue={form?.content} required/></label><label className={styles.fullField}>Public link<input name="link" defaultValue={form?.link} placeholder="/your-public-route"/></label><footer className={styles.modalFooter}><button type="button" className={styles.secondaryButton} onClick={() => setForm(undefined)}>Cancel</button><button className={styles.primaryButton} type="submit">Save {singular}</button></footer></div></form></div>}
    {view && <div className={styles.modalLayer} role="dialog" aria-modal="true"><button className={styles.modalBackdrop} onClick={() => setView(null)} aria-label="Close"/><article className={`${styles.modal} ${styles.viewModal}`}><header className={styles.modalHeader}><div><span className={`${styles.status} ${view.status === 'Published' ? styles.published : styles.draft}`}>{view.status}</span><h2>{view.title}</h2></div><button className={styles.iconButton} onClick={() => setView(null)} aria-label="Close"><AdminIcon name="close"/></button></header><div className={styles.blogMeta}><span>{view.category}</span><span>{view.client}</span><span>{dateLabel(view.publishDate)}</span></div><p className={styles.blogSummary}>{view.shortDescription}</p><div className={styles.blogContent}>{view.content}</div><footer className={styles.modalFooter}><button className={styles.secondaryButton} onClick={() => { setView(null); setForm(view); }}>Edit</button><button className={styles.primaryButton} onClick={() => setView(null)}>Close</button></footer></article></div>}
    {remove && <div className={styles.modalLayer} role="dialog" aria-modal="true"><button className={styles.modalBackdrop} onClick={() => setRemove(null)} aria-label="Close"/><section className={`${styles.modal} ${styles.confirmModal}`}><span className={styles.dangerIcon}><AdminIcon name="trash"/></span><h2>Delete this {singular.toLowerCase()}?</h2><p><strong>{remove.title}</strong> will be removed from this local workspace.</p><footer className={styles.modalFooter}><button className={styles.secondaryButton} onClick={() => setRemove(null)}>Cancel</button><button className={styles.dangerButton} onClick={confirmRemove}>Delete</button></footer></section></div>}
  </AdminShell>;
};
